replicaCount: 1

image:
  repository: rhoai/mecee4520-demo
  tag: v0.1.2
  pullPolicy: IfNotPresent

env_vars:
  - name: MY_ENV_VAR
    value: "Hello from the environment"
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
